App/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'App'  
urlpatterns = [
    # two paths: with or without given image
    path('', views.index, name='index'),
    path('App/imgList.html',views.ListFunc, name='imgList'),
    path('App/results.html',views.result_info, name='results'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib import admin
from django.urls import path,include
#from App import views
#from App.views import index

urlpatterns = [
    path('', include('App.urls', namespace="App")),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'users'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('agreement/', views.AgreementView.as_view(), name='agreement'),
    path('signup/', views.signup, name='signup'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <!-- Required mera tags -->
  <meta charset="UTF-8">
  <meta name="viewpoint" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- bootstrap CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>Nigra and Schizophrenia</title>
</head>
<style>
          body {
            background-color: #041C3A;
            color: #D6B534;
        }
</style>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 END -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'App:index' %}">Nigra and Schizophrenia</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'users:logout' %}">{{ user.username }} (Logout)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'users:signup' %}">sign up</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>